-- 코드를 작성해주세요
SELECT E.YEAR AS YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM (
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
) AS E 
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS M
ON E.YEAR = M.YEAR
ORDER BY E.YEAR ASC, YEAR_DEV ASC